/**
 * Forward Certificate Method (proof-oriented implementation)
 *
 * Core theorem encoded in code:
 * If remainders are generated by r_i = (r_{i-1} * k_i) mod y
 * and r_n = 1, then (product of k_i) mod y is x^{-1} mod y.
 */

function gcd(a, b) {
  let x = Math.abs(a);
  let y = Math.abs(b);
  while (y !== 0) {
    const t = y;
    y = x % y;
    x = t;
  }
  return x;
}

function normalizeMod(a, m) {
  return ((a % m) + m) % m;
}

function validateInputs(x, y) {
  if (!Number.isInteger(x) || !Number.isInteger(y)) {
    return { ok: false, message: "x and y must be integers" };
  }
  if (y <= 1) {
    return { ok: false, message: "y must be > 1" };
  }
  const m = normalizeMod(x, y);
  if (m === 0) {
    return { ok: false, message: "x ≡ 0 (mod y), inverse does not exist" };
  }
  if (gcd(m, y) !== 1) {
    return { ok: false, message: `gcd(${m}, ${y}) != 1, inverse does not exist` };
  }
  return { ok: true, message: "valid" };
}

function verifyCertificate(x, y, multipliers) {
  const valid = validateInputs(x, y);
  if (!valid.ok) {
    return {
      valid: false,
      reason: valid.message,
      remainders: [],
      inverseFromProduct: null
    };
  }

  if (!Array.isArray(multipliers) || multipliers.length === 0) {
    return {
      valid: false,
      reason: "certificate must be a non-empty multiplier array",
      remainders: [],
      inverseFromProduct: null
    };
  }

  const m = normalizeMod(x, y);
  const remainders = [m];
  let r = m;
  let productMod = 1;

  for (const k of multipliers) {
    if (!Number.isInteger(k) || k <= 0) {
      return {
        valid: false,
        reason: `invalid multiplier: ${k}`,
        remainders,
        inverseFromProduct: null
      };
    }
    r = (r * k) % y;
    remainders.push(r);
    productMod = (productMod * k) % y;
  }

  const theoremCheck = (m * productMod) % y === 1;
  const terminalCheck = remainders[remainders.length - 1] === 1;

  return {
    valid: theoremCheck && terminalCheck,
    reason: theoremCheck && terminalCheck
      ? "certificate is valid"
      : "certificate does not terminate at remainder 1",
    remainders,
    inverseFromProduct: theoremCheck ? productMod : null
  };
}

function euclidInverse(x, y) {
  const valid = validateInputs(x, y);
  if (!valid.ok) {
    return { success: false, inverse: null, message: valid.message };
  }

  const m = normalizeMod(x, y);
  let oldR = m;
  let r = y;
  let oldS = 1;
  let s = 0;

  while (r !== 0) {
    const q = Math.floor(oldR / r);
    [oldR, r] = [r, oldR - q * r];
    [oldS, s] = [s, oldS - q * s];
  }

  if (oldR !== 1) {
    return { success: false, inverse: null, message: "no inverse" };
  }

  return {
    success: true,
    inverse: normalizeMod(oldS, y),
    message: "inverse found via Extended Euclid"
  };
}

function forwardInverse(x, y, options = {}) {
  const valid = validateInputs(x, y);
  if (!valid.ok) {
    return {
      success: false,
      inverse: null,
      method: "forward-certificate",
      message: valid.message
    };
  }

  const maxDepth = options.maxDepth ?? 20;
  const maxOffset = options.maxOffset ?? 12;
  const allowEuclidFallback = options.allowEuclidFallback ?? true;
  const requireDecrease = options.requireDecrease ?? true;

  const m = normalizeMod(x, y);
  const offsets = Array.from({ length: Math.max(0, maxOffset) + 1 }, (_, i) => i);

  function dfs(remainder, depth, ks, steps, remainders) {
    if (remainder === 1) {
      return { ks, steps, remainders };
    }
    if (depth >= maxDepth) {
      return null;
    }

    const base = Math.ceil(y / remainder);

    for (const offset of offsets) {
      const k = base + offset;
      const product = remainder * k;
      const next = product % y;

      if (next === 0) {
        continue;
      }
      if (requireDecrease && next >= remainder && next !== 1) {
        continue;
      }

      const line = {
        depth: depth + 1,
        remainderBefore: remainder,
        k,
        product,
        remainderAfter: next
      };

      const found = dfs(
        next,
        depth + 1,
        ks.concat(k),
        steps.concat(line),
        remainders.concat(next)
      );
      if (found) {
        return found;
      }
    }

    return null;
  }

  const found = dfs(m, 0, [], [], [m]);
  if (found) {
    const product = found.ks.reduce((acc, k) => (acc * k) % y, 1);
    const proof = verifyCertificate(m, y, found.ks);

    return {
      success: true,
      inverse: product,
      method: "forward-certificate",
      message: "forward certificate found",
      certificate: found.ks,
      remainders: found.remainders,
      steps: found.steps,
      proofChecked: proof.valid
    };
  }

  if (!allowEuclidFallback) {
    return {
      success: false,
      inverse: null,
      method: "forward-certificate",
      message: "no certificate found within search limits"
    };
  }

  const fallback = euclidInverse(m, y);
  if (!fallback.success) {
    return {
      success: false,
      inverse: null,
      method: "euclid-fallback",
      message: fallback.message
    };
  }

  return {
    success: true,
    inverse: fallback.inverse,
    method: "euclid-fallback",
    message: "forward search failed; recovered by Euclid",
    certificate: null,
    remainders: [m],
    steps: [],
    proofChecked: (m * fallback.inverse) % y === 1
  };
}

module.exports = {
  gcd,
  verifyCertificate,
  forwardInverse,
  euclidInverse
};
